### ISSUE TITLE
Implement login screen

### ISSUE THREAD

**Issue by MihaiPantiru** [code4romania/teacher-workout-ios#1]
[The Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=0%3A1) contains the entire UI of the project. 

You can export any image (asset) directly from Figma. [Here's how](https://drive.google.com/file/d/1KJncuAGFvKEo6zrjC9H3O59auITE0q2h/view). 

**Please do not try to recreate the UI design exactly.** Prioritize using de default UI mobile components and following the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios). The UI objects should be positioned roughly the same as in the Figma screens. 

[The mobile flow can be found in the project Wiki](https://github.com/code4romania/teacher-workout-backend/wiki/Teacher-Workout-Mobile-flow).

_Please define related colors and text & button styles in the corresponding values files. Please extract all text values in the corresponding Localizable files so we can easily adjust them. <3_

---

This is the page any non-logged-in users see when they open the application. 

From here, a user can either log in or create an account. They can create an account using an e-mail and password or by using third parties (Google, Facebook and Apple ID). 

The logo can be found in this attachment. The PNG logo is available, with an SVG version in the works. 
[education4ro-teacher-workout.zip](https://github.com/code4romania/teacher-workout-android/files/6715204/education4ro-teacher-workout.zip)

After a successful login, the user should be redirected to:

* the on-boarding process, if they have just created an account and are logging in for the first time; the user should always be redirected to the first onboarding screen after logging in if they have not yet gone through all of the onboarding screens
* their [Home screen](https://drive.google.com/file/d/1c8ONN6GTeeSGMX9U-wlHfQicNm3T9q6V/view?usp=sharing) if they have already finished the onboarding process

![image](https://user-images.githubusercontent.com/14028425/123404927-03d33380-d5b2-11eb-99f4-390eba05ac12.png)

**Comment by vladstanescu94** [comment]
i'll do this 😄
