### ISSUE TITLE
Implement lesson start screen

### ISSUE THREAD

**Issue by MihaiPantiru** [code4romania/teacher-workout-ios#8]
[The Figma document](https://www.figma.com/file/uLiqrlxmOB5xCppIzmiUXV/Teacher-Workout?node-id=0%3A1) contains the entire UI of the project. 

You can export any image (asset) directly from Figma. [Here's how](https://drive.google.com/file/d/1KJncuAGFvKEo6zrjC9H3O59auITE0q2h/view). 

**Please do not try to recreate the UI design exactly.** Prioritize using de default UI mobile components and following the [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios). The UI objects should be positioned roughly the same as in the Figma screens. 

[The mobile flow can be found in the project Wiki](https://github.com/code4romania/teacher-workout-backend/wiki/Teacher-Workout-Mobile-flow).

_Please define related colors and text & button styles in the corresponding values files. Please extract all text values in the corresponding Localizable files so we can easily adjust them. <3_

---

The lesson's name, the theme, the reading time will be fetched from the corresponding endpoint in the backend. For API use our stagging environment (https://teacher.heroesof.tech/graphql) 

The **Începe lecția** button will take the user to the first content part within the lesson. 
The **Salvează lecția** button will add this lesson to the Saved lessons list in the user object, as well as add it to the **Lecții în curs** list on their profile page. For save use GraphQL mutation **lessonSave**. 
With this ticket, we should only call the mutation and on success to close the modal.

![C38FBF56-EBE0-4526-966F-0D90EA3B49D8](https://user-images.githubusercontent.com/481425/128829131-1aab9cd4-ea05-4fce-bc20-2e78b9ee8f55.png)

**Comment by mihaigpm** [comment]
Working on it.
